### ISSUE TITLE
not able to disable resource detector

### ISSUE THREAD

**Issue by droger88** [open-telemetry/opentelemetry-js-contrib#1780]
## Steps to Reproduce
1. enable auto instrument on k8s
```
 annotations:
        # enable opentelemetry auto-instrument
        instrumentation.opentelemetry.io/inject-nodejs: "my-instrument"
```
2. enable only `env` for resource detector using environment variable
```
...
      containers:
        - name: app
          image: app-image
          envFrom:
            - configMapRef:
                name: my-config
          env:
          - name: OTEL_SERVICE_NAME
            value: my-app
          - name: OTEL_NODE_RESOURCE_DETECTORS
            value: "env"
...
```
3. enable http logs in the application, and I can see it tries to get meta data for gcp and alibaba cloud.
```
HTTP 29: SOCKET ERROR: ECS metadata api request timed out. Error: ECS metadata api request timed out.
    at Timeout._onTimeout (/otel-auto-instrumentation/node_modules/@opentelemetry/resource-detector-alibaba-cloud/build/src/detectors/AlibabaCloudEcsDetector.js:87:29)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

```
HTTP 1: SOCKET ERROR: getaddrinfo ENOTFOUND metadata.google.internal. Error: getaddrinfo ENOTFOUND metadata.google.internal.
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
```
4. we also see some errors when the init container starts, not sure if this will be a problem as well, we are running container as non-root
```
...
cp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/dist/protobuf.min.js': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/dist/protobuf.min.js.map': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/dist': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/ext/debug/README.md': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/ext/debug/index.js': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/ext/debug': Operation not permitted
...
```
## Expected Result
auto instrument should not try to get meta data for google or alibaba cloud
## Actual Result
it tries to query the infra meta data which does not exist
## Additional Details
image version: `otel/autoinstrumentation-nodejs:0.44.0`
