### ISSUE TITLE
Error reading configuration for prometheus in fastify example

### ISSUE THREAD

**Issue by elvus** [open-telemetry/opentelemetry-js-contrib#1888]
### What version of OpenTelemetry are you using?
Latest

### What version of Node are you using?
v20.9.0

### What did you do?
I try to run the fastify example and it's giving me this error
![image](https://github.com/open-telemetry/opentelemetry-js-contrib/assets/24416449/1c69ca3a-f2d6-4e0e-bab8-edbbe636b5ee)

### What did you expect to see?
I expected the Fastify example to run successfully without any errors.

### What did you see instead?
The application did not start as expected.

### Additional context
System: MacOS Sonoma 14.2.1
Processor: M1

### Configuration files:
collector-config.yaml
```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
```
prometheus.yml
```yml
global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: 'collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['collector:9464']
```
docker-compose.yml
```yml
version: "3"
services:
  # Collector
  collector:
    #image: otel/opentelemetry-collector:0.38.0
    image: otel/opentelemetry-collector
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - zipkin-all-in-one
  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
```

**Comment by pichlermarc** [comment]
Hmm, this is not the example we host at the moment (it does not include the prometheus exporter), therefore I think this is not a bug in the example.

Looking at the provided yaml file, it looks like the collector is misconfigured here (providing `endpoint` for a prometheus **receiver** when it should be a prometheus **exporter**)

**Comment by elvus** [comment]
Hi @pichlermarc yes the problem was the collector-config, I fixed it:
```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
  prometheus:
    endpoint: "localhost:9464"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
```
But still not working,  it gives me this error
```json
{"level":30,"time":1704456291397,"pid":3226,"hostname":"MacBook-Pro-de-Mac.local","reqId":"req-1","req":{"method":"POST","url":"/run_test/1","hostname":"localhost:8080","remoteAddress":"::1","remotePort":50323},"msg":"incoming request"}
{"stack":"AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","errors":"Error: connect ECONNREFUSED ::1:55681,Error: connect ECONNREFUSED 127.0.0.1:55681","code":"ECONNREFUSED","name":"AggregateError"}
{"stack":"AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","errors":"Error: connect ECONNREFUSED ::1:55681,Error: connect ECONNREFUSED 127.0.0.1:55681","code":"ECONNREFUSED","name":"AggregateError"}
2024-01-05T12:04:51.756Z sending response
{"level":30,"time":1704456291763,"pid":3226,"hostname":"MacBook-Pro-de-Mac.local","reqId":"req-1","res":{"statusCode":200},"responseTime":365.6292919963598,"msg":"request completed"}
{"stack":"AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","errors":"Error: connect ECONNREFUSED ::1:55681,Error: connect ECONNREFUSED 127.0.0.1:55681","code":"ECONNREFUSED","name":"AggregateError"}
{"stack":"AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","errors":"Error: connect ECONNREFUSED ::1:55681,Error: connect ECONNREFUSED 127.0.0.1:55681","code":"ECONNREFUSED","name":"AggregateError"}
{"stack":"AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","errors":"Error: connect ECONNREFUSED ::1:55681,Error: connect ECONNREFUSED 127.0.0.1:55681","code":"ECONNREFUSED","name":"AggregateError"}
```
And the data isn't showing in zipkin 🥲
