### ISSUE TITLE
Node - TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by Starefossen** [open-telemetry/opentelemetry-js-contrib#1950]
## Steps to Reproduce

Follow the guide for automatic instrumentation: https://opentelemetry.io/docs/languages/js/automatic/

The source code for this application is here: https://github.com/nais/unleash/tree/unleash-v5 and is based on `express` `^4.18.2`.

Environment variables:

```yaml
    - name: NODE_OPTIONS                                                                                                                      
      value: --require @opentelemetry/auto-instrumentations-node/register                                                                               
    - name: OTEL_EXPORTER_OTLP_PROTOCOL                                     
      value: grpc                                                           
    - name: OTEL_NODE_RESOURCE_DETECTORS                                    
      value: env,host,container                                                                                                                         
    - name: OTEL_SERVICE_NAME                                                                                                                           
      value: my-demo                                                                                                                                  
    - name: OTEL_EXPORTER_OTLP_ENDPOINT                                                                                                                 
      value: http://opentelemetry-collector.my-system:4317     
    - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME                               
      valueFrom:                  
        fieldRef:                                                           
          apiVersion: v1                                                    
          fieldPath: metadata.name
    - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME                              
      valueFrom:                                                                                                                                        
        fieldRef:                                                                                                                                       
          apiVersion: v1                                                                                                                                
          fieldPath: spec.nodeName                                          
    - name: OTEL_PROPAGATORS 
      value: tracecontext,baggage,b3                                        
    - name: OTEL_RESOURCE_ATTRIBUTES                                        
      value: k8s.container.name=unleash,k8s.deployment.name=my-demo,k8s.namespace.name=my-unleash,k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_N
AME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.replicaset.name=my-demo-f95cddd45,service.version=v5.9.6-20240221-210653-d96e3be           
    image: europe-north1-docker.pkg.dev/nais-io/nais/images/unleash-v4:v5.9.6-20240221-210653-d96e3be                                                   
```

## Expected Result

It should start properly.

## Actual Result

Application 

### OpenTelemetry Setup Code

```JavaScript
// automatic instrumentation
```

### package.json

```JSON
// https://github.com/nais/unleash/blob/unleash-v5/package.json
{
  "name": "nais-unleash",
  "version": "4.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "all": "yarn lint && yarn test && yarn build",
    "start": "node ./dist/index.js",
    "build-and-start": "tsc && node ./dist/index.js",
    "build": "tsc",
    "test": "jest --coverage --no-cache --silent src/*.test.ts",
    "test:debug": "jest --runInBand --coverage --no-cache --detectOpenHandles src/*.test.ts",
    "lint": "eslint ./src --ext .ts,.tsx",
    "lint:fix": "eslint ./src --ext .js,.jsx,.ts,.tsx --fix"
  },
  "author": "NAIS <aura@nav.no>",
  "license": "MIT",
  "engines": {
    "node": "^20.0.0"
  },
  "dependencies": {
    "@opentelemetry/api": "^1.7.0",
    "@opentelemetry/auto-instrumentations-node": "^0.41.1",
    "google-auth-library": "^9.6.3",
    "jsonwebtoken": "^9.0.2",
    "log4js": "^6.9.1",
    "unleash-server": "5.9.6"
  },
  "devDependencies": {
    "@types/cors": "2.8.17",
    "@types/express": "4.17.21",
    "@types/express-session": "1.17.10",
    "@types/faker": "6.6.9",
    "@types/jest": "^29.5.12",
    "@types/js-yaml": "4.0.9",
    "@types/jsonwebtoken": "^9.0.5",
    "@types/make-fetch-happen": "10.0.4",
    "@types/node": "20.11.19",
    "@types/semver": "7.5.7",
    "@types/stoppable": "1.1.3",
    "@types/supertest": "6.0.2",
    "@types/type-is": "1.6.6",
    "@types/uuid": "9.0.8",
    "@typescript-eslint/eslint-plugin": "7.0.2",
    "@typescript-eslint/parser": "7.0.2",
    "eslint": "^8.56.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.1.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-no-only-tests": "^3.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "jest": "^29.7.0",
    "nock": "^13.5.3",
    "prettier": "^3.2.5",
    "supertest": "^6.3.4",
    "ts-jest": "^29.1.2",
    "ts-node": "^10.9.2",
    "typescript": "5.3.3"
  }
}
```

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'forEach')
    at iterateStack (/app/node_modules/@wesleytodd/openapi/lib/generate-doc.js:74:24)
    at /app/node_modules/@wesleytodd/openapi/lib/generate-doc.js:17:5
    at Array.forEach (<anonymous>)
    at generateDocument (/app/node_modules/@wesleytodd/openapi/lib/generate-doc.js:16:26)
    at OpenApiMiddleware (/app/node_modules/@wesleytodd/openapi/index.js:42:29)
    at /app/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:214:37
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at arguments.<computed> (/app/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:210:41)
    at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:518:28)
    at SendStream.error (/app/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/app/node_modules/send/index.js:417:12)
```
