### ISSUE TITLE
nestjs-core: extend tes-all-versions cover

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-contrib#2197]
The [@nestjs/core instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-nestjs-core) defines an open range for supported versions `>=4.0.0`, which is capped in #2196 to the latest current major version.

However, since the instrumentation was last updated, the package [released few more major versions](https://www.npmjs.com/package/@nestjs/core?activeTab=versions), which the instrumentation will attempt to patch, are not part of the current [`.tav.yaml` range](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-nestjs-core/.tav.yml)

```yaml
"@nestjs/core":
  - versions: "^8.2.0 || 8.1.2 || 8.1.1 || 8.0.11 || 8.0.9 || 8.0.6"
    peerDependencies:
        - "@nestjs/common@^8.0.0"
        - "@nestjs/microservices@^8.0.0"
        - "@nestjs/platform-express@^8.0.0"
        - "@nestjs/websockets@^8.0.0"
        - "rxjs@^7.1.0"
    commands: npm run test

  - versions: "^7.6.17 || 7.6.15 || 7.6.13 || 7.6.12"
    peerDependencies:
        - "@nestjs/common@^7.0.0"
        - "@nestjs/microservices@^7.0.0"
        - "@nestjs/platform-express@^7.0.0"
        - "@nestjs/websockets@^7.0.0"
        - "rxjs@^6.0.0"
    commands: npm run test

  - versions: "6.11.11"
    peerDependencies:
        - "@nestjs/common@^6.0.0"
        - "@nestjs/microservices@^6.0.0"
        - "@nestjs/platform-express@^6.0.0"
        - "@nestjs/websockets@^6.0.0"
        - "rxjs@^6.0.0"
    commands: npm run test

```

This issue is to add those versions to the test-all-versions yaml, make sure instrumentation works for these versions (exaime any potential changes to the functions we patch with new versions) and consider upgrading the [version in `devDependencies`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/c1c3650be0c506407b5820d13db9dea1de50e1bc/plugins/node/opentelemetry-instrumentation-nestjs-core/package.json#L49).
