### ISSUE TITLE
Add `test-all-versions` setup for `@nestjs/core`

### ISSUE THREAD

**Issue by Rauno56** [open-telemetry/opentelemetry-js-contrib#805]
We currently test the instrumentation only on one version of `@nestjs/core`, which is not even the most popular one. Since the testing already takes major versions into account this could potentially be a low hanging fruit adding coverage for a few hundred thousand downloads/week.

Stats from 29. December 2021.

```
┌─────────┬───────────┬──────────────┬──────────────┬───────────┬──────────┐
│ (index) │  version  │     time     │     tags     │ downloads │ ratio(%) │
├─────────┼───────────┼──────────────┼──────────────┼───────────┼──────────┤
│    0    │  '8.2.4'  │ '2021-12-17' │ [ 'latest' ] │  133610   │   18.5   │
│    1    │ '7.6.18'  │ '2021-06-17' │      []      │  130111   │   18.1   │
│    2    │  '8.2.3'  │ '2021-11-22' │      []      │   94952   │   13.2   │
│    3    │ '7.6.15'  │ '2021-03-22' │      []      │   39197   │   5.4    │
│    4    │ '6.11.11' │ '2020-03-03' │      []      │   35012   │   4.9    │
│    5    │  '8.0.6'  │ '2021-08-05' │      []      │   32406   │   4.5    │
│    6    │  '8.1.2'  │ '2021-10-25' │      []      │   25893   │   3.6    │
│    7    │ '7.6.17'  │ '2021-05-18' │      []      │   20304   │   2.8    │
│    8    │  '8.0.9'  │ '2021-09-30' │      []      │   16741   │   2.3    │
│    9    │  '8.1.1'  │ '2021-10-14' │      []      │   16727   │   2.3    │
└─────────┴───────────┴──────────────┴──────────────┴───────────┴──────────┘
Ratio of downloads through versions shown in the table: 75.61%
Total weekly downloads: 720,765
```

See #783, #792 or #786 for reference.

**Comment by matteoga** [comment]
hi @Rauno56 , i can take care of this one :) 
Given that nestJS is comprised of multiple packages, other than `@nestjs/core`, and some of them are being imported in both instrumentation / tests ( ie: `@nestjs/common` ) , unless you have objectios, i will use `tav` `peerDependencies` to ensure all package versions are matchine, so something like
```
"@nestjs/core":
  - versions: "^8.2.4" 
    peerDependencies:
        - "@nestjs/common@^8.2.4"
        - "@nestjs/microservices@^8.2.4"
        - "@nestjs/platform-express@^8.2.4"
        - "@nestjs/websockets@^8.2.4"
    commands: npm run test
    
  - versions: "8.2.3" 
    peerDependencies:
        - "@nestjs/common@8.2.3"
        - "@nestjs/microservices@8.2.3"
        - "@nestjs/platform-express@8.2.3"
        - "@nestjs/websockets@8.2.3"
    commands: npm run test
```
sounds good ?
